### ISSUE TITLE
Doesn't work...

### ISSUE THREAD

**Issue by salihmarangoz** [pobrn/hid-ite8291r3#1]
How can I debug the module? There is no printf or logging in the code. I can use ite8291r3-ctl but this kernel module doesn't work.

**Comment by pobrn** [comment]
You should at least see a line like this in the kernel message buffer:
```
<date> <hostname> kernel: hid_ite8291r3 0003:048D:CE00.0002: probing
```
(e.g. `journalctl -b0 -k | grep hid_ite8291r3`)

If you don't see any such lines, or even any lines that contain "hid_ite8291r3", then that means there are no currently supported devices on your system (or they are already used by other drivers).

Please check the output of `ls -l /sys/bus/hid/devices`, the middle two numbers are the vendor id and product id:
```
lrwxrwxrwx ... 0003:048D:CE00.0007 -> ../../../devices/pci0000:00/0000:00:14.0/usb1/1-6/1-6:1.1/0003:048D:CE00.0007
```
(e.g. here `048D` is the vendor id, `CE00` is the product id).


Note, that if you have the `tuxedo_keyboard` kernel module, then that already binds to the keyboard HID device, so this one cannot.

**Comment by salihmarangoz** [comment]
I removed tuxedo_keyboard and others via "rmmod" but still doesn't work after reloading again. The code with journactl prints nothing. I can use the device with ite8291r3-ctl but not this one. The device is free but I can't use it. Is there any way to debug this module, at least with printf, etc.? Also my lsusb output:

```
Bus 004 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 003 Device 003: ID 8087:0029 Intel Corp. 
Bus 003 Device 004: ID 048d:6004 Integrated Technology Express, Inc. 
Bus 003 Device 002: ID 05e3:0608 Genesys Logic, Inc. Hub
Bus 003 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
Bus 002 Device 002: ID 05e3:0620 Genesys Logic, Inc. USB3.2 Hub
Bus 002 Device 003: ID 0bda:0316 Realtek Semiconductor Corp. USB3.0-CRW
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 004: ID 04f2:b71a Chicony Electronics Co., Ltd HD Webcam
Bus 001 Device 006: ID 046d:c328 Logitech, Inc. Corded Keyboard K280e
Bus 001 Device 005: ID 09da:5871 A4Tech Co., Ltd. 
Bus 001 Device 003: ID 05e3:0610 Genesys Logic, Inc. 4-port hub
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub
```

**Comment by pobrn** [comment]
> Is there any way to debug this module, at least with printf, etc.?

There are already debug logs in the module, e.g. a successful probe looks like this:
```
kernel: hid_ite8291r3 0003:048D:CE00.0007: probing
kernel: hid_ite8291r3 0003:048D:CE00.0007: usb interface: 1
kernel: hid_ite8291r3 0003:048D:CE00.0007: hidraw1: USB HID v1.10 Device [ITE Tech. Inc. ITE Device(8291)] on usb-0000:00:14.0-6/input1
kernel: hid_ite8291r3 0003:048D:CE00.0007: firmware version: 13 07 00 00
```

If you have used `ite8291r3-ctl`, then that unbinds the `usbhid` module from the device, therefore reloading the HID driver won't do anything. A quick and dirty workaround is to run `sudo rmmod usbhid && sudo modprobe usbhid`. Alternatively, you can bind it again by running `echo <device name> | sudo tee /sys/bus/usb/drivers/usbhid/bind`, where the device name is something like `1-6:1.1` (you can find the available devices in `/sys/bus/usb/devices`, you need to find which one corresponds to the appropriate interface of the USB device).

**Comment by salihmarangoz** [comment]
Thanks! `sudo rmmod usbhid && sudo modprobe usbhid` did the trick.
